### PR TITLE
Add support for drafting on Dexterity add and edit forms

### PR DESCRIPTION
**Pull request by datakurre**
Work in progress. Will probably be part of Mosaic.

TODO, at least:
- disable Archetypes -support by default (I don't have experience about it and Mosaic is Dexterity only)
- make autosave (during inline validation) its own behavior
- fix tests, refactor to use p.a.testing and add Travis-CI

This should already work with Mosaic: can draft persistent tiles both on the add form and edit form.

### CODE REVIEW

**Comment by datakurre** [comment]
I did look into p.a.z3cformdrats, but it looked too generic and complex. I used it as an example to make add support (as simple support as possible) only for DX add and edit forms.

**Comment by datakurre** [comment]
@hvelarde @tisto Would you be able to enable Travis-CI for plone.app.drafts? Thanks!

**Comment by datakurre** [comment]
Travis-CI enabled would still be great. There should now be passing test for both Plone 4 and Plone 5 on Travis-CI and tests are refactored to use plone.app.testing.

https://travis-ci.org/datakurre/plone.app.drafts

**Comment by hvelarde** [comment]
done!

**Comment by datakurre** [comment]
@hvelarde Thanks.

Someone should try out, if p.a.drafts works already with c.cover and p.a.tiles 1.x. It might. What it does, it makes persistent tiles to be saved into a temporary location (portal_drafts tool) until the page is saved. (And p.tiles and p.a.tiles have supported it from the beginning.)

**Comment by datakurre** [comment]
@hvelarde It might even replace iterate / working copy support in simple cases

**Comment by hvelarde** [comment]
@datakurre which, sadly, is not our case :-(

anyway I'll take a look on this also when we finished our current project.

**Pull request merged**
