### PR TITLE
Do not set cookie values twice

### PR DESCRIPTION
**Pull request by vangheem**

### CODE REVIEW

**Comment by datakurre** [comment]
Those Travis errors for Plone 4 seem completely unrelated, but this is still the first commit to break the build. I wonder, what has changed in the latest Plone 4.3.x releases to break that.

Of course, the nicest thing would be to fix Plone 4.x tests, but an option would be to
- branch the master to 1.0.x (and the build probably fails there)
- drop official Plone 4.x support here and configure the Travis to allow failures on Plone 4.x (or remove the tests completely)
- update setup.py so that the next release would be 1.1.0

**Comment by vangheem** [comment]
FWIW, this issue is fixing a symptom of a different problem I think. What was happening was on live sites the cookie value would get set once correct and then it'd run through a second time with the incorrect path--one that included the site id. This would work fine when working local but would break things when deployed between virtualhostmonster. So on live sites they would edit tiles, hit cancel and it's actually save those changes yet.

**Comment by datakurre** [comment]
Thanks! Sounds like an issue, whose fix would make great 1.0.1 release, if only that 4.3.x issue is resolved :/ I could not immediately see from code, how those tests could fail that way on Plone 4.x only. We'll see, if that flickers.

**Comment by gforcada** [comment]
@vangheem @datakurre after doing some cleanup #5 and updating the test infrastructure #4 I took the time to rebase this branch on top of current master, let's see if the flickering test is still around.

**Comment by vangheem** [comment]
Alright, updated again and fixed some of the CSRF issues as well. I will merge when/if it passes this time.

**Pull request merged**
